FROM grafana/grafana:13.1.0

COPY --chown=grafana:grafana ops/grafana/provisioning /etc/grafana/provisioning
COPY --chown=grafana:grafana ops/grafana/dashboards /var/lib/grafana/dashboards

EXPOSE 3000
