apiVersion: 1

datasources:
  - name: Promotion Radar Prometheus
    uid: promotion-radar-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 3.13.1
      cacheLevel: High
      timeInterval: 15s
